interface ReportData {
  userName: string;
  reportDate: string;
  totalQuizzes: number;
  averageScore: number;
  totalTimeSpent: number;
  studyStreak: number;
  subjectPerformance: Array<{
    subject: string;
    score: number;
    attempts: number;
  }>;
  recentQuizzes: Array<{
    date: string;
    course: string;
    score: number;
    timeTaken: number;
  }>;
}

export async function generatePDFReport(data: ReportData): Promise<void> {
  const content = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Performance Report - ${data.userName}</title>
  <style>
    @page {
      size: A4;
      margin: 20mm;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
      line-height: 1.6;
      color: #1f2937;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
    .header {
      text-align: center;
      margin-bottom: 40px;
      border-bottom: 3px solid #3b82f6;
      padding-bottom: 20px;
    }
    .header h1 {
      color: #3b82f6;
      margin: 0 0 10px 0;
      font-size: 32px;
    }
    .header p {
      margin: 5px 0;
      color: #6b7280;
    }
    .summary {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 20px;
      margin-bottom: 40px;
    }
    .stat-card {
      background: #f3f4f6;
      padding: 20px;
      border-radius: 8px;
      border-left: 4px solid #3b82f6;
    }
    .stat-card h3 {
      margin: 0 0 10px 0;
      color: #6b7280;
      font-size: 14px;
      font-weight: 500;
      text-transform: uppercase;
    }
    .stat-card .value {
      font-size: 32px;
      font-weight: bold;
      color: #1f2937;
    }
    .section {
      margin-bottom: 40px;
    }
    .section h2 {
      color: #1f2937;
      border-bottom: 2px solid #e5e7eb;
      padding-bottom: 10px;
      margin-bottom: 20px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 15px;
    }
    th, td {
      padding: 12px;
      text-align: left;
      border-bottom: 1px solid #e5e7eb;
    }
    th {
      background: #f9fafb;
      font-weight: 600;
      color: #374151;
    }
    tr:hover {
      background: #f9fafb;
    }
    .score-high {
      color: #10b981;
      font-weight: bold;
    }
    .score-medium {
      color: #f59e0b;
      font-weight: bold;
    }
    .score-low {
      color: #ef4444;
      font-weight: bold;
    }
    .footer {
      margin-top: 60px;
      padding-top: 20px;
      border-top: 2px solid #e5e7eb;
      text-align: center;
      color: #6b7280;
      font-size: 12px;
    }
    @media print {
      body {
        padding: 0;
      }
      .section {
        page-break-inside: avoid;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Performance Report</h1>
    <p><strong>${data.userName}</strong></p>
    <p>Generated on ${data.reportDate}</p>
  </div>

  <div class="summary">
    <div class="stat-card">
      <h3>Total Quizzes</h3>
      <div class="value">${data.totalQuizzes}</div>
    </div>
    <div class="stat-card">
      <h3>Average Score</h3>
      <div class="value">${data.averageScore}%</div>
    </div>
    <div class="stat-card">
      <h3>Time Spent</h3>
      <div class="value">${data.totalTimeSpent}m</div>
    </div>
    <div class="stat-card">
      <h3>Study Streak</h3>
      <div class="value">${data.studyStreak} days</div>
    </div>
  </div>

  <div class="section">
    <h2>Subject Performance</h2>
    <table>
      <thead>
        <tr>
          <th>Subject</th>
          <th>Average Score</th>
          <th>Attempts</th>
        </tr>
      </thead>
      <tbody>
        ${data.subjectPerformance.map(item => `
          <tr>
            <td>${item.subject}</td>
            <td class="${item.score >= 70 ? 'score-high' : item.score >= 50 ? 'score-medium' : 'score-low'}">${item.score}%</td>
            <td>${item.attempts}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  </div>

  <div class="section">
    <h2>Recent Quiz History</h2>
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Course</th>
          <th>Score</th>
          <th>Time Taken</th>
        </tr>
      </thead>
      <tbody>
        ${data.recentQuizzes.map(quiz => `
          <tr>
            <td>${quiz.date}</td>
            <td>${quiz.course}</td>
            <td class="${quiz.score >= 70 ? 'score-high' : quiz.score >= 50 ? 'score-medium' : 'score-low'}">${quiz.score}%</td>
            <td>${quiz.timeTaken}m</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  </div>

  <div class="footer">
    <p>This report was automatically generated by Sure Success CBT Platform</p>
    <p>&copy; ${new Date().getFullYear()} Sure Success CBT. All rights reserved.</p>
  </div>
</body>
</html>
`;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(content);
    printWindow.document.close();

    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print();
      }, 250);
    };
  }
}
